
#nuget version is nly changed by  RELEASE TAG 
version: 1.0.0-dev-{build} 

image: Visual Studio 2022
pull_requests:
  do_not_increment_build_number: false

init:
  - ps: |
      git config --global core.autocrlf input
      $env:CAN_PUBLISH = $true

      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }
        try
        {         
          Update-AppveyorBuild -Version $ver 
          Write-Host "Update-AppveyorBuild Success to change version to TAG: '$env:APPVEYOR_REPO_TAG_NAME'"   -ForegroundColor Green          
        }
        catch
        {
          Write-Host "Update-AppveyorBuild Fail to change version to TAG: '$env:APPVEYOR_REPO_TAG_NAME'"   -ForegroundColor Red
          Write-Host "Exception Error: $PSItem.Exception.Message" -ForegroundColor Red
          $env:CAN_PUBLISH = $false
        }
      }
  - ps: |
      Write-Host "APPVEYOR_BUILD_VERSION='$env:APPVEYOR_BUILD_VERSION'" -ForegroundColor Yellow
      Write-Host "APPVEYOR_REPO_TAG_NAME= '$env:APPVEYOR_REPO_TAG_NAME'" -ForegroundColor Yellow       

configuration: Release

skip_commits:
  files:    
    - '**/*.md'    
    - .gitignore
    - .editorconfig
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update changelog.*/

 
build_script:
- cmd: dotnet build src/Compatibility.CompilerFeatures.sln  -c Release --version-suffix %APPVEYOR_BUILD_VERSION% 

test_script: 
- cmd: dotnet test test/Compatibility.CompilerFeatures.Test/ 

after_test:
- cmd: dotnet pack src/Compatibility.CompilerFeatures/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%  
- ps: |
    $version=$env:APPVEYOR_BUILD_VERSION
    $allow_push=$env:APPVEYOR_REPO_TAG -eq "true"
   
 
artifacts:
- path: .\build\Compatibility.CompilerFeatures.*.nupkg
  name: lib
 

deploy:
- provider: GitHub
  auth_token:
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: /.*(\.|\.s)nupkg|o2p_exe|sha256/            
  prerelease: false  
  on:
    APPVEYOR_REPO_TAG: true

- provider: NuGet
  api_key:
    secure: XBvbm69UE+d1cuM8+VBfwMyjHDcAa79w0TBygcZsPZcl88AaLKN1EvI7KI8/K9Am
  on:
    APPVEYOR_REPO_TAG: true # Deploy on tag push only.
    branch: master          # Release from master branch only.
    

# myget
#https://www.myget.org/feed/Packages/compilerfeatures
- provider: NuGet
  server: https://www.myget.org/F/CompilerFeatures/api/v2/package
  api_key:
    secure: QAHjX2gqddFX2cNhMNqweMTGQ89q++ezKnQvdAcinY5D1rwbj2vkWeFsTykm4koA  
  on:    
    branch: develop          
  